import { citySchema } from '../../city/entities/city.schema.js';
import { teamSchema } from '../../team/entities/team.schema.js';
// Trusted relational schema metadata shared by the repository and mapper.
import type { Table } from './types/schedule.types.js';
export const scheduleSchema: Record<Table, Record<string, string>> = {
  cities: citySchema,
  teams: teamSchema,
  tournaments: {
    id: 'Uint64',
    name: 'Utf8',
    season: 'Utf8',
    type: 'Utf8',
    startDate: 'Date',
    endDate: 'Date',
    templateId: 'Uint64?',
    createdAt: 'Timestamp',
    updatedAt: 'Timestamp',
  },
  stages: {
    id: 'Uint64',
    tournamentId: 'Uint64',
    parentStageId: 'Uint64?',
    type: 'Utf8',
    format: 'Utf8',
    name: 'Utf8',
    sortOrder: 'Uint32',
    settings: 'Json?',
    createdAt: 'Timestamp',
    updatedAt: 'Timestamp',
  },
  tournament_team_slots: {
    id: 'Uint64',
    tournamentId: 'Uint64',
    stageId: 'Uint64',
    groupName: 'Utf8?',
    slotName: 'Utf8',
    teamId: 'Uuid?',
    seed: 'Uint32?',
    createdAt: 'Timestamp',
    updatedAt: 'Timestamp',
  },
  matches: {
    id: 'Uint64',
    tournamentId: 'Uint64',
    stageId: 'Uint64?',
    matchDate: 'Timestamp',
    cityId: 'Uuid',
    homeSlotId: 'Uint64?',
    awaySlotId: 'Uint64?',
    homeTeamId: 'Uuid?',
    awayTeamId: 'Uuid?',
    homeScore: 'Int32?',
    awayScore: 'Int32?',
    createdAt: 'Timestamp',
    updatedAt: 'Timestamp',
  },
  bracket_slots: {
    id: 'Uint64',
    matchId: 'Uint64',
    side: 'Utf8',
    sourceType: 'Utf8',
    sourceStageId: 'Uint64?',
    sourceGroupName: 'Utf8?',
    sourcePosition: 'Uint32?',
    sourceMatchId: 'Uint64?',
    resolvedTeamId: 'Uuid?',
    createdAt: 'Timestamp',
    updatedAt: 'Timestamp',
  },
  tournament_templates: {
    id: 'Uint64',
    name: 'Utf8',
    description: 'Utf8?',
    version: 'Uint32',
    isActive: 'Bool',
    schema: 'Json',
    createdAt: 'Timestamp',
    updatedAt: 'Timestamp',
  },
};
